# Generated by Django 5.2.7 on 2025-10-16 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('activity', models.CharField(choices=[('H', 'Hiking'), ('C', 'Camping'), ('S', 'Sight-seeing'), ('W', 'Swimming')], default='H', max_length=1)),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.park')),
            ],
        ),
    ]
